== クイックスタート
:imagesdir: img/クイックスタート


GUIツール(sit-wt-app.jar)を使ってテストプロジェクトとテストスクリプトを作成します。 +
同梱のサンプルWebサイトとテストスクリプトで直ぐに動かすことができます。

**※実行にはJava11が必要となります。**

. https://repo.maven.apache.org/maven2/io/sitoolkit/wt/sit-wt-app/3.0.0-beta.3/sit-wt-app-3.0.0-beta.3.jar[jarファイル]をダウンロードします。
. ダウンロードしたjarファイルをダブルクリックで実行するとGUIツールが起動します。以降はGUIツールの操作です。
. テストプロジェクトを作成するフォルダを選択します。
. **Sample** メニュー > **Start** を選択します。サンプルWebサイトが起動し、サンプルテストスクリプトが生成されます。
. 生成されたサンプルテストスクリプトが画面左の **testscriptフォルダ** 内にあるので選択します。
. **Test** メニュー > **Run** (または **Debug**) を選択し、テストを実行します。

**※JNIエラーダイアログが表示される場合は、古いバージョンのJavaを使用している可能性があります。** +
**「sit-wt-app.jar」のプロパティを開き、「Opens with」をJava 11の「javaw.exe」に変更して下さい。**

=== CLIでのテスト実行

テストプロジェクトでテストスクリプトを一度に実行するには、CLIツール（Mavenプラグイン）を使用します。 +
以下はCLIでサンプルWebサイトのテストを実行する手順です。

. GUIツールを起動し、サンプルWebサイトを起動します。
. 以下に示すコマンドを実行します。使用OSのコマンドを参照して下さい。


==== Windows

....
cd \path\to\testproject
mvnw verify -DbaseUrl=http://localhost:8280
mvnw sit-wt:open-report
....


==== macOS

....
cd \path\to\testproject
./mvnw verify -DbaseUrl=http://localhost:8280
./mvnw sit-wt:open-report
....


=== Learn More

クイックスタートは以上です。  

次は実際にテストスクリプトを作成し、自動テストを動かしてみてください。 +
また、Web Testerには自動テストを行うための便利な機能がたくさんあります。 +
以下の項目を参照し、是非試してみてください。  

* <<_テストスクリプトの仕様,**テストスクリプトの仕様**>>
+
こちらで仕様を参照しながら、テストスクリプトを作成してみてください。

* <<_デバッグ機能,**デバッグ機能**>>
+
テストが想定外の動きをした際の原因特定には、デバッグ機能が有用です。

* <<_テストするブラウザの変更,**テストするブラウザの変更**>>
+
Chrome以外のブラウザでもテストが実行できます。

* <<_ブラウザ操作をテストスクリプトに記録する,**ブラウザ操作をテストスクリプトに記録する**>>
+
Selenium IDEを使用し、ブラウザ操作からテストスクリプトを作成することができます。

* <<_jenkinsでテストする,**Jenkinsで自動テストを実行する**>>
+
Web TesterをJenkinsで実行することができます。
