= Jenkinsでテストする


ここではSIT-WTのテストスクリプトをJenkinsで実行するための設定手順を説明します。SIT-WTはMavenに統合されているため、Jenkinsのジョブの作り方は一般的なMavenプロジェクトのものと同じです。手順のおおよその流れは以下の通りです。

. SIT-WTのプロジェクトをバージョン管理ツールに登録
. Jenkinsのジョブを作成
. 作成したジョブを実行

手順を実施するにあたり、以下の作業が済んでいることを前提とします。

* バージョン管理ツールのセットアップ
* Jenkinsのセットアップ
* <<クイックスタート.adoc#,クイックスタート>>で取得したpom.xmlで、SIT-WTのプロジェクトを作成
* テストスクリプトの作成
* バージョン管理ツールのリポジトリを作成、プロジェクト資源を登録

バージョン管理ツールはSubversionやGitなど、Jenkinsが対応しているものである必要があります。



=== Jenkinsのジョブを作成

Jenkinsでジョブを作成します。

. ダッシュボードで「**新規ジョブ作成**」をクリックします。
. 新規ジョブ作成ページで「**Mavenプロジェクトのビルド**」を選択し、「**OK**」ボタンをクリックします。
. ジョブ設定ページでバージョン管理リポジトリの情報とMavenのビルドの情報を設定します。ビルドの「**ゴールとオプション**」には「**clean verify**」を指定します。
. 「**保存**」ボタンをクリックし、ジョブを保存します。

以上でジョブの作成手順は終了です。


==== 接続先の基底URLを変更する

テスト対象の接続先の基底URLは**baseUrl**システムプロパティを使って指定します。**baseUrl**は「**ゴールとオプション**」に以下の様に追加します。

....
-DbaseUrl=http://<test-server>/ clean verify
....

これにより、テストスクリプト内のopen操作で指定されたパスは全てbaseUrlを基底とするようになります。例えばパスに「**input.html**」が指定されている場合、open操作はテスト実行時に「**http&#58;//<test-server>/input.html**」を開きます。



=== テスト実行と結果の確認

作成したJenkinsのジョブを実行します。ジョブが終了すると、ジョブのワークスペースにテスト結果が出力されます。

....
_ジョブのワークスペース_ /target/evicence_yyyyMMddhhmmss
....


==== スクリーンショットに関する注意

SIT-WTのテストをJenkinsのジョブで実行した場合、Javascriptで表示させるダイアログ、つまりwindow.alert, window.confirm等で表示されるダイアログのスクリーンショットは取得できません。
なお、通常のページのスクリーンショットは取得できます。